# Generated by Django 5.0.6 on 2024-05-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_restaurant', '0002_category_customer_order_customerorderlink_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='FoodCategory',
        ),
        migrations.RenameModel(
            old_name='OrderDetail',
            new_name='FoodOrderDetail',
        ),
        migrations.RenameModel(
            old_name='Type',
            new_name='FoodType',
        ),
    ]
