# Generated by Django 5.0.6 on 2024-05-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_restaurant', '0003_rename_category_foodcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact_info',
            new_name='contact_information',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='name',
        ),
    ]
