# Generated by Django 5.0.6 on 2024-05-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_restaurant', '0006_remove_customerorderdetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderdetail',
            name='food_item',
            field=models.ManyToManyField(through='app1_restaurant.FoodOrderDetail', to='app1_restaurant.fooditem'),
        ),
    ]
