# Generated by Django 5.0.6 on 2024-05-23 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_restaurant', '0008_alter_order_order_status_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderdetail',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
