# Generated by Django 5.0.6 on 2024-05-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_restaurant', '0009_customerorderdetail_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
