# Generated by Django 5.0.6 on 2024-05-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_restaurant', '0010_remove_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ManyToManyField(through='app1_restaurant.CustomerOrderLink', to='app1_restaurant.customer'),
        ),
    ]
