# Generated by Django 5.0.6 on 2024-05-23 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_restaurant', '0012_rename_customer_order_customer_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderlink',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='app1_restaurant.customer'),
        ),
    ]
