# Generated by Django 5.0.6 on 2024-05-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_restaurant', '0013_alter_customerorderlink_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorderdetail',
            old_name='food_item',
            new_name='food_item_details',
        ),
    ]
