# Generated by Django 5.0.6 on 2024-05-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_restaurant', '0014_rename_food_item_customerorderdetail_food_item_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorderdetail',
            old_name='food_item_details',
            new_name='food_order_details',
        ),
    ]
