# Generated by Django 5.0.6 on 2024-05-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_restaurant', '0016_rename_customer_order_details_order_customer_order_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_order_links',
            new_name='customer_who_ordered',
        ),
    ]
