# Generated by Django 5.0.6 on 2024-05-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_restaurant', '0017_rename_customer_order_links_order_customer_who_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='type',
            new_name='cuisine_type',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='name',
            new_name='title',
        ),
    ]
